
server:
  port: 8765

zuul:
  prefix: /api
  routes:
    account:
      path: /accounts/**
      serviceId: account-service
    customer:
      path: /customers/**
      serviceId: customer-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false

ribbon:
  eureka:
    enabled: true
info:
  compoent: Edge Server

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
